name: Basic Workflow
on: [push]

jobs:
  basic-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a simple command
        run: echo "Hello! This workflow was triggered by a push"
