name: Basic Workflow
on: [push]

jobs:
  basic-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run a simple command
      run: echo "Hello! This workflow was triggered by a push"

    - name: Get variable
      run: echo "Here's a variable ${{ vars.SOME_VAR }}"

    - name: Get secret
      run: echo "And here's a secret ${{ secrets.SOME_SECRET }}"
